### ISSUE TITLE
feature: splitting wide emotes into multiple emotes

### ISSUE THREAD

**Issue by SquirrelKiev** [ike-gg/Tetra#23]
General idea here is an option to have something like widePeepoHappy as widePeepoHappy1, widePeepoHappy2, etc, so wide emotes can show as:
![image](https://github.com/ike-gg/Tetra/assets/41798511/49ecc592-5825-49cf-a5f2-037aa43c15df)
instead of 
![image](https://github.com/ike-gg/Tetra/assets/41798511/411302bf-07a5-4059-99e7-75c55c61fe12)

**Comment by ike-gg** [comment]
just pushed changes with feature to split emotes. during final checkout of emote you have ability to choose a splitting option

<img width="751" alt="image" src="https://github.com/ike-gg/Tetra/assets/67127723/a97a61b3-3522-429d-9c6d-642e5ed748e8">

**Comment by SquirrelKiev** [comment]
Seems to work pretty well, thanks for doing this! glad it gives you the option to choose how many parts to split into too
just curious, as the emote splitting part is at the final stage (post optimization), could that lead to tetra trying to optimizing a wide gif too much to fit into 1 emote when it wouldve fit better into the split ones? or is that a non issue
